### PR TITLE
some minor fixes for cyclus-deps on linux

### PR DESCRIPTION
**Pull request by scopatz**
Might help mac out too.

### CODE REVIEW

**Comment by gidden** [comment]
thanks for the pr @scopatz, is this testable? also, should this be PR'd into develop?

**Comment by gidden** [comment]
err whoops, wrong repo. sorry!

**Comment by gidden** [comment]
let me know when you have a link available

**Comment by scopatz** [comment]
Note that I had to add some scripts here to be able to build the deps. Testing now. I'll ping when it is actually working.

**Comment by rwcarlsen** [comment]
@scopatz - is this still valid now that this repo has been repurposed for release scripts, etc.?

**Comment by scopatz** [comment]
Probably not, withdrawing.

**Pull request closed without merging**
